version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api

  api:
#    image: gcr.io/dockerregistry-195816/github-hcv57-coinrank-chat:2113cd01524d11772704678950bbff0178d8f283
    image: coinrankchat
    entrypoint: gunicorn --bind 0.0.0.0 coinrankchat.api.server
    environment:
      ELASTIC_HOST: elasticsearch
    depends_on:
     - elasticsearch
  telegram:
#    image: gcr.io/dockerregistry-195816/github-hcv57-coinrank-chat:2113cd01524d11772704678950bbff0178d8f283
    image: coinrankchat
    volumes:
      - ./coinrankchat.session:/usr/src/app/coinrankchat.session
    entrypoint: python -m coinrankchat.main
    environment:
      ELASTIC_HOST: elasticsearch
      TELEGRAM_API_ID: $TELEGRAM_API_ID
      TELEGRAM_API_HASH: $TELEGRAM_API_HASH
      TELEGRAM_PHONE: $TELEGRAM_PHONE
    depends_on:
     - elasticsearch
  elasticsearch:
    image: elasticsearch
    volumes:
      - elastic-data-volume:/usr/share/elasticsearch/data

volumes:
  elastic-data-volume:
